baseURL = "/"
languageCode = "en-us"
title = "NingBo Solar Tech"
theme = "solar-tech"
paginate = 6

copyright = "Ningbo Solar Import & Export Co., Ltd."


# Main Menu
[[menu.main]]
name = "HOME"
url = ""
weight = 1
[[menu.main]]
name = "ABOUT"
url = "about"
weight = 2
[[menu.main]]
name = "PRODUCT"
url = "product"
weight = 3
[[menu.main]]
name = "CONTACT"
url = "contact"
weight = 4

# Footer menu
[[menu.footer]]
name = "Über uns"
URL = "about"
weight = 1

[[menu.footer]]
name = "Projekt"
URL = "project"
weight = 2

[[menu.footer]]
name = "Dienstleistung"
URL = "service"
weight = 3

[[menu.footer]]
name = "Preise"
URL = "pricing"
weight = 4

[[menu.footer]]
name = "Häufige Fragen"
URL = "faq"
weight = 5

[[menu.footer]]
name = "Kontakt"
URL = "contact"
weight = 6


